name: 'Secrets to .env'
description: 'Easily turn global and branch specific Github secrets into a .env'
author: Jordan Skomer
inputs:
  secrets:
    required: true
  output_name: # id of input
    description: 'The name of the file to output'
    required: false
    default: '.env'
  output_dir:
    description: 'The directory where to output the file to'
    required: false
    default: '.'
  no_cache:
    description: 'Disable caching'
    required: false
    default: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
branding:
  icon: 'key'
  color: 'green'
runs:
  using: 'node12'
  main: 'dist/index.js'
