name: 'pre-release'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  changelog: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ github.token }}
