name: 'release'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  changelog: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: semantic-release
        uses: ahmadnassri/action-semantic-release@v2.1.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
